# configs/EB-Navigation.yaml
model_name: gpt-4o-mini
down_sample_ratio: 1
model_type: remote
language_only: False
eval_sets: []
chat_history: False
n_shots: 10
multistep: False
resolution: 500
exp_name: baseline
env_feedback: True
tp: 1